# Generated by Django 3.0.2 on 2020-02-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commits',
            name='branch',
            field=models.CharField(default='master', max_length=50),
        ),
        migrations.AddField(
            model_name='commits',
            name='isdiff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commits',
            name='pulltime',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-15 20:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commits',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
