# Generated by Django 3.0.2 on 2020-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_auto_20200212_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commits',
            name='pulltime',
            field=models.DateTimeField(),
        ),
    ]
