# Generated by Django 3.0.2 on 2020-02-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0003_auto_20200212_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commits',
            name='pulltime',
        ),
    ]
