# Generated by Django 3.0.2 on 2020-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Docid', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('Document', models.CharField(max_length=10000)),
                ('sha', models.CharField(max_length=50)),
                ('isdiff', models.IntegerField(default=0)),
                ('branch', models.CharField(default='master', max_length=50)),
            ],
        ),
    ]
